// src/components/ScreenTab.vue
<script setup lang="ts">
import LayoutPanel from "./LayoutPanel.vue";
import PropertiesPanel from "./PropertiesPanel.vue";
import BlocksPanel from "./BlocksPanel.vue";
import { ref } from "vue";
import { AIScreen } from "aia-kit/ai_screen.js";
import { AIComponent } from "aia-kit/ai_component.js";

const props = defineProps<{ screen: AIScreen }>();

const selectedComponent = ref(props.screen.form);

function onComponentSelected(component: AIComponent) {
    selectedComponent.value = component;
}

</script>

<template>
    <div class="flex">
        <LayoutPanel :form="$props.screen.form" @componentSelected="onComponentSelected" />
        <PropertiesPanel :component="selectedComponent" />
        <BlocksPanel :blocksXml="$props.screen.blocks" />
    </div>
</template>

// src/components/ScreenTab.tsx
import type {Screen} from "aia-kit";
import {useState} from "react";
import {Container, Grid} from "@mantine/core";
import {LayoutPanel} from "./LayoutPanel.js";
import {PropertiesPanel} from "./PropertiesPanel.js";
import {BlocksPanel} from "./BlocksPanel.js";

export function ScreenTab({screen}: { screen: Screen }) {
    const [selected, setSelected] = useState(screen.form)
    return (
        <Container fluid>
            <Grid>
                <Grid.Col span={3}>
                    <LayoutPanel form={screen.form} selected={selected} setSelected={setSelected}/>
                </Grid.Col>
                <Grid.Col span={3}>
                    <PropertiesPanel component={selected}/>
                </Grid.Col>
                <Grid.Col span={6}>
                    <BlocksPanel blocksXml={screen.blocks}/>
                </Grid.Col>
            </Grid>
        </Container>
    )
}
