// src/Explorer.tsx
import {Center, Loader, Tabs} from '@mantine/core';
import {useQuery} from "@tanstack/react-query";
import {AIAReader} from "aia-kit";
import {IconDeviceMobile, IconIcons, IconPuzzle} from "@tabler/icons-react";
import {ScreenTab} from "./components/ScreenTab.js";
import {ExtensionsTab} from "./components/ExtensionsTab.js";
import {AssetsTab} from "./components/AssetsTab.js";
import {OverviewTab} from "./components/OverviewTab.js";

export function Explorer({file}: { file: File }) {

    const {status, data: project, error} = useQuery({
        queryKey: ['aia'],
        queryFn: () => AIAReader.parse(file)
    })

    if (status === 'pending') {
        return <Center h="calc(100dvh - var(--app-shell-header-height))"><Loader/></Center>
    }

    if (status === 'error') {
        return <pre>{JSON.stringify(error, null, 2)}</pre>
    }

    return (
        <Tabs defaultValue="overview" keepMounted>
            <Tabs.List>
                <Tabs.Tab value="overview"><b>{project.name}</b></Tabs.Tab>
                <Tabs.Tab value="assets"
                          leftSection={<IconIcons size='1.2rem' stroke={1.5}/>}>
                  Assets
                </Tabs.Tab>
                <Tabs.Tab value="extensions"
                          leftSection={<IconPuzzle size='1.2rem' stroke={1.5}/>}>
                  Extensions
                </Tabs.Tab>
                {
                    project.screens.map((screen) => (
                        <Tabs.Tab key={screen.name} value={screen.name}
                                  leftSection={<IconDeviceMobile size='1.2rem' stroke={1.5}/>}>
                          {screen.name}
                        </Tabs.Tab>
                    ))
                }
            </Tabs.List>
            <Tabs.Panel value="overview">
                <OverviewTab project={project}/>
            </Tabs.Panel>
            <Tabs.Panel value="assets">
                <AssetsTab assets={project.assets}/>
            </Tabs.Panel>
            <Tabs.Panel value="extensions">
                <ExtensionsTab exts={project.extensions}/>
            </Tabs.Panel>
            {
                project.screens.map((screen) => (
                    <Tabs.Panel key={screen.name} value={screen.name}>
                        <ScreenTab screen={screen}/>
                    </Tabs.Panel>
                ))
            }
        </Tabs>
    )
}

// src/Explorer.vue
<script setup lang="ts">
import { Icon123, IconDeviceMobile, IconIcons, IconPuzzle } from "@tabler/icons-vue";
import ScreenTab from "./components/ScreenTab.vue";
import ExtensionsTab from "./components/ExtensionsTab.vue";
import AssetsTab from "./components/AssetsTab.vue";
import OverviewTab from "./components/OverviewTab.vue";

import { ref } from 'vue';
import { AIProject } from "aia-kit/ai_project.js";
import { AIScreen } from 'aia-kit/ai_screen.js';

const props = defineProps<{ project: AIProject }>();

const activeTab = ref('overview');
const selectedScreen = ref<AIScreen | null>(null);

const onMenuSelect = (index: string) => {
    if (index === 'overview' || index === 'assets' || index === 'extensions') {
        activeTab.value = index;
    } else {
        activeTab.value = 'screen';
        selectedScreen.value = props.project.screens.find(screen => screen.name === index)!;
    }
}
</script>

<template>
    <el-container style="height: calc(100vh - 60px)">
        <el-aside>
            <el-menu @select="onMenuSelect">
                <el-menu-item index="overview">
                    <el-icon>
                        <Icon123 />
                    </el-icon>
                    Project
                </el-menu-item>
                <el-menu-item index="assets">
                    <el-icon>
                        <IconIcons />
                    </el-icon>
                    Assets
                </el-menu-item>
                <el-menu-item index="extensions">
                    <el-icon>
                        <IconPuzzle />
                    </el-icon>
                    Extensions
                </el-menu-item>
                <el-sub-menu index="screens">
                    <template #title>
                        <el-icon>
                            <IconDeviceMobile />
                        </el-icon>
                        Screens
                    </template>
                    <el-menu-item v-for="screen in project.screens" :key="screen.name" :index="screen.name">
                        {{ screen.name }}
                    </el-menu-item>
                </el-sub-menu>
            </el-menu>
        </el-aside>

        <el-main class="p-0">
            <template v-if="activeTab === 'overview'">
                <OverviewTab :project="project" />
            </template>
            <template v-else-if="activeTab === 'assets'">
                <AssetsTab :assets="project.assets" />
            </template>
            <template v-else-if="activeTab === 'extensions'">
                <ExtensionsTab :exts="project.extensions" />
            </template>
            <template v-else-if="activeTab === 'screen'">
                <ScreenTab :screen="selectedScreen" />
            </template>
        </el-main>
    </el-container>
</template>
